name: Build binaries
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
      - run: curl -s -O https://ricketyspace.net/go/build.sh
      - run: sh build.sh fern
      - uses: actions/upload-artifact@v4
        with:
          name: fern-binaries
          path: fern-*
